### ISSUE TITLE
About stable-diffusion-2-1

### ISSUE THREAD

**Issue by Cococyh** [AttendAndExcite/Attend-and-Excite#14]
Hi,

I apply your method on stable-diffusion-1.5, it works.
But when I load the pre-trained model stable-diffusion-2-1, I meet this error, it seems like the pipeline is not work.

Seed: 0
  0%|                                                                                                    | 0/50 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/run.py", line 90, in <module>
    main()
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/run.py", line 73, in main
    image = run_on_prompt(prompt=config.prompt,
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/run.py", line 44, in run_on_prompt
    outputs = model(prompt=prompt,
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/pipeline_attend_and_excite.py", line 506, in __call__
    max_attention_per_index = self._aggregate_and_get_max_attention_per_token(
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/pipeline_attend_and_excite.py", line 224, in _aggregate_and_get_max_attention_per_token
    attention_maps = aggregate_attention(
  File "/home/ubuntu/12T_1/szs/code/stable_diffusion/stable-diffusion-webui/Attend-and-Excite-diffusers/utils/ptp_utils.py", line 232, in aggregate_attention
    out = torch.cat(out, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by AttendAndExcite** [comment]
Hi @Cococyh, thanks for your interest!
looks like the attention maps are not being saved by the controller.
we have a pending pull request to upgrade the version of diffusers that may help solve your issue.
if the issue persists after the PR is merged, we will try to help investigating this issue :)

**Comment by Cococyh** [comment]
Hi @AttendAndExcite, thanks for your reply!
But actually I already have the diffusers==0.12.1.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/85297785/217122556-8ba27e9f-5ab2-4b22-9ed7-b8af53323d35.png">

**Comment by XavierXiao** [comment]
I think this is because when you have 768-sized image, there is not an attention dimension 16, you need to adjust the attention dimension correspondingly. 

The forked codes is runnable for SDv2, but it seems like it is not effective. I found that the iterative refinement will always reach the max iter and the loss does not change much. I am trying to investigate what's wrong.

**Comment by AttendAndExcite** [comment]
Hi @XavierXiao, and @Cococyh.
@Cococyh, as mentioned by @XavierXiao, if your model does not have 16x16 attention maps you would need to adjust to work on the most semantic attention resolution. I’d recommend visualizing all the attention resolutions separately  and determining which gives the maps that correspond to the generated objects best.

@XavierXiao, which prompts did you work on? It could be an issue of expressiveness of Stable Diffusion, have you tried the prompts from the paper?

**Comment by XavierXiao** [comment]
I am on a smaller GPU so I cannot run 768*768 generation. So I try [stable diffusion 2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base) which is a 512*512 model, with prompt `A frog and a pink bench` which is in the paper. But I found the gradient to be very small so the iterative refinement will always reach the max _iter, and the sample will look very similar to the original SD's sample. 

Since it is still a 512 model, I use the default hyper parameters. 

Here is a screenshot. As you can see, I print out the grad norm and it is small. The loss does not decrease much.
<img width="2048" alt="Screen Shot 2023-02-06 at 10 11 33 PM" src="https://user-images.githubusercontent.com/14303231/217162936-7a4c89a8-afb5-420a-b9e9-7fa2abd200e3.png">

**Comment by XavierXiao** [comment]
And the samples with (top) and without (bottom) A&E.

Maybe some configs need to be changed? You can have a try with the given SD version and prompt.

![A frog and a pink bench_with ae](https://user-images.githubusercontent.com/14303231/217163514-d01ec31b-8dee-4e3f-b9ab-b0d2ad06f0a1.png)
![A frog and a pink bench](https://user-images.githubusercontent.com/14303231/217163552-705054a7-048c-4d37-8734-80eba9587e26.png)

**Comment by AttendAndExcite** [comment]
Thanks for the additional information, @XavierXiao!
We will do our best to investigate the issue as well but in the meantime, here are some tips that may be useful in case you’d like to explore a solution:

1. Since this is a newly trained model, I’d take a look at the visualizations of the attention maps at different resolutions (to make sure the 16x16 maps are indeed still the most semantic ones).
2. I see that the model uses a different text encoder. We perform an additional Softmax operation to discard the \<sot\> token, it could be that this is not necessary with the ViT-H text encoder (not sure but the attention visualization should answer this question).
3. This is less likely, but it could be that you need to tune the hyperparameters for this case separately (you can try increasing the [scale factor](https://github.com/AttendAndExcite/Attend-and-Excite/blob/main/config.py#L29)).

**Comment by Cococyh** [comment]
@AttendAndExcite @XavierXiao, As your say, I set attention dimension to 24 then it looks like I get a nice result, the result picture is 768*768.
The prompt is "a cat and a dog".

Try 1. dog has a max attention of 0.0006623268127441406
         Try 2. dog has a max attention of 0.0007052421569824219
         Try 3. dog has a max attention of 0.000751495361328125
         Try 4. dog has a max attention of 0.0008020401000976562
         Try 5. dog has a max attention of 0.0008549690246582031
         Try 6. dog has a max attention of 0.0009126663208007812
         Try 7. dog has a max attention of 0.0009746551513671875
         Try 8. dog has a max attention of 0.001041412353515625
         Try 9. dog has a max attention of 0.0011148452758789062
         Try 10. dog has a max attention of 0.0011930465698242188
         Try 11. dog has a max attention of 0.0012788772583007812
         Try 12. dog has a max attention of 0.0013704299926757812
         Try 13. dog has a max attention of 0.0014696121215820312
         Try 14. dog has a max attention of 0.0015773773193359375
         Try 15. dog has a max attention of 0.0016927719116210938
         Try 16. dog has a max attention of 0.0018167495727539062
         Try 17. dog has a max attention of 0.0019502639770507812
         Try 18. dog has a max attention of 0.0020923614501953125
         Try 19. dog has a max attention of 0.0022449493408203125
         Try 20. dog has a max attention of 0.0024089813232421875
         Exceeded max number of iterations (20)! Finished with a max attention of 0.0024089813232421875
         Finished with loss of: 0.99755859375
Iteration 0 | Loss: 0.9976
  5%|█████                                                                                                 | 1/20 [00:23<07:20, 23.20s/it]Iteration 1 | Loss: 0.9805
 10%|██████████▏                                                                                           | 2/20 [00:24<03:02, 10.13s/it]Iteration 2 | Loss: 0.9365
 15%|███████████████▎                                                                                      | 3/20 [00:25<01:41,  5.95s/it]Iteration 3 | Loss: 0.8213
 20%|████████████████████▍                                                                                 | 4/20 [00:26<01:04,  4.00s/it]Iteration 4 | Loss: 0.7100
 25%|█████████████████████████▌                                                                            | 5/20 [00:27<00:43,  2.91s/it]Iteration 5 | Loss: 0.6167
 30%|██████████████████████████████▌                                                                       | 6/20 [00:28<00:31,  2.26s/it]Iteration 6 | Loss: 0.5049
 35%|███████████████████████████████████▋                                                                  | 7/20 [00:29<00:23,  1.84s/it]Iteration 7 | Loss: 0.4082
 40%|████████████████████████████████████████▊                                                             | 8/20 [00:30<00:18,  1.57s/it]Iteration 8 | Loss: 0.3638
 45%|█████████████████████████████████████████████▉                                                        | 9/20 [00:31<00:15,  1.39s/it]Iteration 9 | Loss: 0.3447
 50%|██████████████████████████████████████████████████▌                                                  | 10/20 [00:32<00:12,  1.26s/it]Iteration 10 | Loss: 0.4019
 55%|███████████████████████████████████████████████████████▌                                             | 11/20 [00:33<00:10,  1.18s/it]Iteration 11 | Loss: 0.3867
 60%|████████████████████████████████████████████████████████████▌                                        | 12/20 [00:34<00:08,  1.12s/it]Iteration 12 | Loss: 0.3931
 65%|█████████████████████████████████████████████████████████████████▋                                   | 13/20 [00:35<00:07,  1.09s/it]Iteration 13 | Loss: 0.4028
 70%|██████████████████████████████████████████████████████████████████████▋                              | 14/20 [00:36<00:06,  1.06s/it]Iteration 14 | Loss: 0.4424
 75%|███████████████████████████████████████████████████████████████████████████▊                         | 15/20 [00:37<00:05,  1.03s/it]Iteration 15 | Loss: 0.5391
 80%|████████████████████████████████████████████████████████████████████████████████▊                    | 16/20 [00:38<00:04,  1.02s/it]Iteration 16 | Loss: 0.5000
 85%|█████████████████████████████████████████████████████████████████████████████████████▊               | 17/20 [00:39<00:03,  1.02s/it]Iteration 17 | Loss: 0.6055
 90%|██████████████████████████████████████████████████████████████████████████████████████████▉          | 18/20 [00:40<00:02,  1.01s/it]Iteration 18 | Loss: 0.5586
 95%|███████████████████████████████████████████████████████████████████████████████████████████████▉     | 19/20 [00:41<00:00,  1.00it/s]Iteration 19 | Loss: 0.8472
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.10s/it]

![a cat and a dog](https://user-images.githubusercontent.com/85297785/217178500-18832e8b-db7c-49d6-ac30-ef4689229e64.png)

**Comment by XavierXiao** [comment]
@Cococyh Can you try a more complicated example like "a frog and a pink bench"? As I say above the loss  hardly decrease.

**Comment by Cococyh** [comment]
@XavierXiao 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/85297785/217188178-5fec741c-42c0-413c-8d29-259a94414642.png">

**Comment by AttendAndExcite** [comment]
@XavierXiao @Cococyh the loss appears to be quite high for the cat and the dog too- this indicates that it may be an issue of the normalization of the probabilities. We will do our best to look into this ASAP :)

**Comment by XavierXiao** [comment]
I found that by changing[ this line ](https://github.com/evinpinar/Attend-and-Excite-diffusers/blob/main/pipeline_attend_and_excite.py#L198) to `attention_for_text = attention_maps[:, :, 1:8]` improves the convergence a lot on SD2.1. This is just a stupid way to hard-code, ideally the 8 should be `len(non_padded_token_ids)`. This makes sense because out of 77 tokens, there is a <sot>, a <eot> and the remaining ones are all padded, which should not be included in the computation. I think this should be done in SD v1 as well.

**Comment by AttendAndExcite** [comment]
Thanks @XavierXiao, this actually makes a lot of sense, as I mentioned above, since the model uses a different text encoder the attention values may vary. It is entirely possible that the attention value of \<eot\> is high for SD 2.1 therefore removing it helps the attention values be closer to 1 and then the optimization is easier.
This was not the case for SD 1.4, so it didn’t matter.

**Comment by AttendAndExcite** [comment]
Hi @Cococyh, and @XavierXiao, thanks for the discussion! Our code now officially supports SD 2.1 via the `sd_2_1` parameter (see our README and `generate_images.ipynb` notebook for details).
