### ISSUE TITLE
gpu v100 16G RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by xyxxmb** [AttendAndExcite/Attend-and-Excite#18]
What is the minimum gpu memory to run?

**Comment by AttendAndExcite** [comment]
Hi @xyxxmb, thanks for your interest!
Please see [this issue](https://github.com/AttendAndExcite/Attend-and-Excite/issues/15) and [this issue](https://github.com/AttendAndExcite/Attend-and-Excite/issues/6).
It could happen because you are attempting a combination that is out of distribution, generally (e.g., in the examples from our notebook) it shouldn’t happen.
