### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by aisagarw** [AttendAndExcite/Attend-and-Excite#6]
I have been running the notebooks on a 16GB t4. In some cases, it runs well. But in some other cases (the observation is that loss values don't seem to go down much over iterations in many such cases), it throws up CUDA out of memory error in between the iterations itself. Why is it the case that it works well for the same number of iterations for certain prompts but not for others?

For instance, it works fine for a prompt like **a _cow_ and _dog_ standing ​with a _cat_** . But at the same time, for prompts like **a boy cutting a birthday cake wearing a _hat_** and **an _elephant_ with a _crown_ standing next to a man​**, it throws memory errors within around 10 iterations. (The italics represent the subjects)

Am I missing something? What can be the probable reasons behind something like this?

**Comment by Meatfucker** [comment]
On a 24gb 3090 I have seen it hit a bit over 18gb with complex prompts.

**Comment by AttendAndExcite** [comment]
Hi @aisagarw, thanks for your interest!
In all our experiments the memory consumption did not exceed 16gb.
Since each step optimizes a single neglected token, the number of optimized tokens should not impact the consumption.
Additionally, the text is always at a fixed length of 77 tokens so I’m not sure the length of the text should impact that either.
Could you please share additional details? Seeds etc., we will do our best to look into it :)

**Comment by aisagarw** [comment]
Sure! Following are the exact details:

```
prompt = "a **boy** cutting a **birthday** cake wearing a **hat**"
seeds = [21]
```

I actually didn't change any of the default values in the code (explain.ipynb) apart from the prompt and corresponding subject tokens. Thanks much for your response!

**Comment by AttendAndExcite** [comment]
thanks @aisagarw, it seems that your prompt ("an elephant with a crown standing next to a man​") probably resides outside the distribution that SD has learned for textual descriptions (see the limitations section of our paper). This triggers the iterative refinement for the maximal number of steps which increases the memory consumption beyond 16gb.
in general, as mentioned in the paper, since we do not fine-tune the generative model, our results are limited by the expressive power of SD.

**Comment by aisagarw** [comment]
Thanks much for your insights and response. But one observation I had was, that for the same prompt as mentioned above, the training went fine when only **elephant** and **crown** were the two subject tokens. Whereas, in case where 3 subject tokens namely **elephant**, **crown** and **man** were given, the above mentioned memory issue occurred. 

Is it maybe that the optimization becomes difficult when there are multiple neglected subject tokens?

**Comment by 6Roy** [comment]
Hello,sorry to bother you.I have some puzzles:When the requirement to generate man is added,  iterative refinement is applied (to the tag "man"), and memory consumption increases.So why will lead to this memory consumption increases and the generated image is as follows(not right). As you exampled,it did support 3-4 subjects, when will not result in memory consumption increases?
![image](https://github.com/yuval-alaluf/Attend-and-Excite/assets/72113285/122e474c-5fef-4e7f-93a2-67423fbf3b35)
